title: Susann and Erik's wedding!
email: kusmabite@gmail.com
description: Information about our wedding.
baseurl: ""
url: "https://29-06-2019.com"

exclude: [Gemfile, Gemfile.lock, .editorconfig]
markdown: kramdown
